### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by edi-sipka** [chelmerrox/awesome-books-es6#2]
@chelmerrox this is amazing! Everything works very fine and you did everything that was supposed to be in the project.
There is nothing more I would like to say.

**Comment by soulemanou-software** [comment]
> @chelmerrox this is amazing! Everything works very fine and you did everything that was supposed to be in the project. There is nothing more I would like to say.

### Suggestions (optional)
- Add a remove message when the user clicks on the remove button.

**Comment by chelmerrox** [comment]
Thanks for the review! 😃👍🏽
