### ISSUE TITLE
Peer to peer review: Losalini_Ayesha_Eva

### ISSUE THREAD

**Issue by BucurEva87** [chelmerrox/awesome-books-es6#3]
## What goes for this project

- Linter rules are folllowed
- Good use of HTML5 semantics
- JS Modules are used for code separation
- Good user experience overall

## Suggestions

- When a book is removed from the books list and no other books are present in the list the list itself (div container) should be removed

**Comment by chelmerrox** [comment]
Resolved. Thanks for the review! 🙂👍🏽
